name: 'Verify PR Labels'
author: 'Aios Dave'
description: 'Verify that the PR has a valid label'
branding:
  icon: 'check'
  color: 'red'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  valid-labels:
    description: 'List of valid labels'
    required: true
  post-review:
    description: 'Post review after check'
    required: false
    default: 'false'
  post-comment:
    description: 'Post a custom comment after check fails'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://theparticles/verify-pr-label-action'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}
    - ${{ inputs.post-review }}
    - ${{ inputs.post-comment }}
